name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: '20 2 1,15 * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: ghcr.io
      REGISTRY_IMAGE_NAME: ghcr.io/${{ github.repository }}
    strategy:
      fail-fast: false
      matrix:
        imageName:
          - "8.0-alpine"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Target "base" - build'
        # try to build twice to suppress random network issues with Github Actions
        run: >-
          sed -i 's~^[ \t]*~~' data/${{ matrix.imageName }}/Dockerfile
          && (docker build -f data/${{ matrix.imageName }}/Dockerfile --target "base" -t "ci-target:base" ./
          || docker build -f data/${{ matrix.imageName }}/Dockerfile --target "base" -t "ci-target:base" ./)

      - name: 'Target "base" - test'
        # try to build twice to suppress random network issues with Github Actions
        run: >-
          sed -i 's~^[ \t]*~~' data/${{ matrix.imageName }}/Dockerfile
          && (docker build -f data/${{ matrix.imageName }}/Dockerfile --target "base__test" -t "ci-target:base__test" ./
          || docker build -f data/${{ matrix.imageName }}/Dockerfile --target "base__test" -t "ci-target:base__test" ./)

      - name: 'Target "base" - display layer sizes'
        run: >-
          docker history --no-trunc --format "table {{.CreatedSince}}\t{{.Size}}\t{{.CreatedBy}}" $(docker inspect --format="{{.Id}}" "ci-target:base")
          && docker images --no-trunc --format "Total size: {{.Size}}\t{{.ID}}" | grep $(docker inspect --format="{{.Id}}" "ci-target:base") | cut -f1
          && php analyse-layers.php "ci-target:base__test"
          && php analyse-layers.php "ci-target:base__test" "ci-target:base"
